name: Deploy Trojan VPN

on: [push, workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          sudo apt update
          sudo apt install -y trojan

      - name: Create Trojan configuration
        run: |
          cat > /etc/trojan/config.json <<EOF
          {
            "run_type": "server",
            "local_addr": "0.0.0.0",
            "local_port": 443,
            "remote_addr": "cdn-tanzania.marmot-cloud.com",
            "remote_port": 443,
            "password": [
              "e84854ab-9bd9-46e8-a968-d92d06cc69bb"
            ],
            "ssl": {
              "cert": "/path/to/your/cert.pem",
              "key": "/path/to/your/key.pem",
              "sni": "cdn-tanzania.marmot-cloud.com"
            },
            "websocket": {
              "enabled": true,
              "path": "/trojan-ws",
              "host": "alibaba.drivereurope.online"
            }
          }
          EOF

      - name: Start Trojan
        run: sudo systemctl restart trojan
