{
  "inbounds": [],
  "outbounds": [
    {
      "mux": {
        "enabled": false
      },
      "protocol": "trojan",
      "settings": {
        "servers": [
          {
            "address": "cdn-tanzania.marmot-cloud.com", 
            "port": 443,
            "password": "e84854ab-9bd9-46e8-a968-d92d06cc69bb", 
            "level": 8
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": true,
          "serverName": "cdn-tanzania.marmot-cloud.com"
        },
        "wsSettings": {
          "path": "/trojan-ws",
          "headers": {
            "Host": "alibaba.drivereurope.online"
          }
        }
      },
      "tag": "TROJAN"
    }
  ],
  "policy": {
    "levels": {
      "8": {
        "connIdle": 300,
        "downlinkOnly": 1,
        "handshake": 4,
        "uplinkOnly": 1
      }
    }
  }
}
